fileTitle: タイトル
resizePix:
  - 0
  - 1024
# ignoreWatermark:
#   - 1024
readDir:
  - ../../sample JPG/target
distDir: ../../sample JPG/resize
watermark: src/sample-watermark.png
# defaultWatermarkPosition:
#   - North
#   - West
# watermarkColor: auto
# colorTiefQuality: 50
# colorTiefQuality_watermarkArea: 1
# watermarkColorSelectionWeight:
#   - 1.0
#   - -0.5
#   - 1.5
# defaultLens: lens:laowa105mm
constTag:
  - tea81p
quality: 97
watermarkWidthRate : 0.1
watermarkMarginRate: 0.02
copyright: (c) tea ( @tea0828 )
descriptionTemplate : <a href="https://www.facebook.com/masashibat/" rel="nofollow">Facebook</a> | <a href="https://twitter.com/tea0828" rel="nofollow">Twitter</a> | <a href="https://www.instagram.com/gogo_tea/" rel="nofollow">Instagram</a>
